[package]
name = "turbo-tasks-malloc"
version = "0.1.0"
description = "A wrapper around mimalloc or the system allocator that tracks allocations"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[dependencies]


[target.'cfg(not(any(target_os = "linux", target_family = "wasm")))'.dependencies]
mimalloc = { version = "0.1.48", features = [
  "v3",
  "extended",
], optional = true }

[target.'cfg(all(target_os = "linux", not(target_family = "wasm")))'.dependencies]
mimalloc = { version = "0.1.48", features = [
  "v3",
  "extended",
  "local_dynamic_tls",
], optional = true }

[features]
custom_allocator = ["dep:mimalloc"]
default = ["custom_allocator"]
