[package]
name = "turbo-persistence"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = []
verify_sst_content = []
strict_checks = []
stats = ["quick_cache/stats"]
print_stats = ["stats"]
verbose_log = []

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bitfield = { workspace = true }
byteorder = { workspace = true }
dashmap = { workspace = true}
either = { workspace = true }
jiff = "0.2.10"
lzzzz = "1.1.0"
memmap2 = "0.9.5"
nohash-hasher = { workspace = true }
parking_lot = { workspace = true }
pot = "3.0.0"
qfilter = { version = "0.2.4", features = ["serde"] }
quick_cache = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
thread_local = { workspace = true }
tracing = { workspace = true }
turbo-bincode= { workspace = true }
twox-hash = { workspace = true }
zstd = { version = "0.13.2", features = ["zdict_builder"] }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
rayon = { workspace = true }
tempfile = { workspace = true }
turbo-tasks-malloc = { workspace = true }

[[bin]]
name = "sst_inspect"
path = "src/bin/sst_inspect.rs"

[lints]
workspace = true

[[bench]]
name = "mod"
harness = false
